name: imtools
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=21.2.4
  - pytorch=1.11.0=py3.10_cuda11.3_cudnn8.2.0_0
  - torchvision=0.12.0=py310_cu113
  - torchaudio=0.11.0=py310_cu113
  - cudatoolkit=11.3.1
  - scipy=1.7.3
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - jupyterlab=3.3.2
  - ipywidgets=7.7.0
  - tqdm=4.62.3
  - toolz=0.11.2
  - autopep8=1.6.0
  - flake8=4.0.1
  - flake8-quotes=3.3.1
  - mypy=0.941
  - pip:
      - tensorboard==2.8.0
      - torch-tb-profiler==0.4.0
      - kornia==0.6.3
      - opencv-contrib-python==4.5.5.64
      - colour-demosaicing==0.2.1
      - rawpy==0.17.0
      - mat73==0.58
      - exifread==2.3.2
      - python-dotenv==0.19.2
      - typed-argument-parser==1.7.2
      - invoke==1.6.0
